### ISSUE TITLE
Bintray has shut down

### ISSUE THREAD

**Issue by gwillz** [graze/docker-php-alpine#36]
These images heavily depend on a custom repo hosted on Bintray, which as of May 1st doesn't work.

Relevant issue:
https://github.com/codecasts/php-alpine/issues/131

So I guess it's waiting game until they decide when and where they're going to move.

**Comment by biggianteye** [comment]
Thanks. I'll try to address this at some point.

**Comment by h-bragg** [comment]
Originally it was required as the updated versions were not in the main alpine packages repo. They might be now, and if so moving to the official one will make more sense.

We did have to swap around every time a new version came out tho which was very annoying.

**Comment by gwillz** [comment]
Ah that makes sense. So this only affects PHP versions 7.3, 7.4 and 8.0.

Those are all in the main repos, at least the core components.
- Alpine 3.12 - PHP 7.3
- Alpine 3.13 - PHP 7.4 and 8.0

I don't know how to patch and test this repo. Happy to have a stab though.
